# mkdocs serve -a 127.0.0.1:8000
site_name: LPMS | Новая система управления обучением
repo_url: https://github.com/mmmylnikov/lpms
repo_name: mmmylnikov/lpms
nav:
  - Добро пожаловать!: index.md
  - С чего начать:
    - start/index.md
    - Установка системы:
      - Запуск из Docker compose: start/install/compose-up.md
      - Сборка из Docker compose: start/install/compose-build.md
      - Сборка из исходников: start/install/src.md
    - Переменные окружения: start/env.md
    - Зависимоcти: start/requirements.md
  - Описание системы:
    - 1. Цель проекта: terms/object.md
    - 2. Описание системы: terms/description.md
    - 3. Предлагаемый стек технологий: terms/stack.md
    - 4. Требования к дизайну: terms/styling.md 
    - 5. ER-модель: terms/erd.md
  - Скриншоты: 
    - Авторизация и профили: screenshots/auth.md
    - Обучение: screenshots/learn.md
  - Журнал разработки: 
    - Задачи: devlog/todo.md
    - Версии: devlog/log.md
theme: 
  icon:
    repo: fontawesome/brands/github
  logo: images/keyboard.svg
  favicon: images/favicon.svg
  name: material
  language: ru
  features:
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.code.select
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Переключиться в темный режим
      primary: grey
      accent: brown
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Переключиться в светлый режим
      primary: brown
      accent: grey
extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mmmylnikov/lpms
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC-OVMPlMA3-YCIeg4z5z23A
    - icon: fontawesome/brands/chrome
      link: http://www.moscowpython.ru/
    - icon: fontawesome/brands/python
      link: https://learn.python.ru/
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - search


copyright: |
  <img src="https://mmmylnikov.github.io/lpms-docs/images/made-in-russia-sign-en.png" width="36px"></img> &copy; 2024 <a href="https://learn.python.ru/" target="_blank">LEARN PYTHON</a> | курсы программирования на Python